load("@rules_pkg//:pkg.bzl", "pkg_tar", "pkg_deb")

pkg_deb(
    name = "zlib_package",
    maintainer = "bazel",
    description = "zlib package",
    package = "zlib",
    version = "1.2.11",
    data = "zlib_package.tar.gz"
)